version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01

    working_directory: $HOME/tags


    steps: 
      - checkout
      - run: |
             mkdir /tmp/artifacts
             bash $HOME/tags/circledir/missman.sh php
      - store_artifacts: 
          path: /tmp/missing.txt
