version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01

    working_directory: $HOME/circledir

    steps: 
      - run: |
             token="$(curl -sSL "https://auth.docker.io/token?service=registry.docker.io&scope=repository:circleci/php:pull" | jq --raw-output .token)"
             list="$(curl -s -H "Authorization: Bearer "${token}"" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "https://registry-1.docker.io/v2/circleci/php/tags/list" | sed 's/.*\[//' | sed 's/\]\"\}//' | tr -d '"')"
             cols="$(awk -F',' '{print NF}' <<< "$list")"
             echo COLS=$cols
             start=1
             for ((i=1 ; i<=$cols ; i++))
             do
             tag="$(cut -d',' -f"$i" <<< "$list")"
             response="$(curl -iI -H "Authorization: Bearer $token" "https://registry-1.docker.io/v2/circleci/php/manifests/"${tag}"")"
             response_stripped="$(echo "$response" | tr '\r' ' ' | tr '\n' ' ' | sed 's/ \{3,\}/ /g' | sed 's/   / /g')"
             missing="$(grep -o "404" <<< "$response_stripped")"
             if [ "$missing" == 404 ]
             then
             echo -e ""$tag" is missing!" >> missing.txt
             echo -e "$tag is missing!"
             else
             echo "lcd soundsystem - we still got it"
             fi
             done

       
      - store_artifacts: 
          path: $HOME/circledir      
       
