version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01

    working_directory: $HOME/circledir

    steps: 
      - run: |
             bash -x script_test
       
      - store_artifacts: 
          path: $HOME/circledir      
       
