version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01

    working_directory: $HOME

    steps: 
      - checkout
      - run: bash script3
      - store_artifacts:
          path: .
             
