version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01

    working_directory: $HOME

    steps: 
      - run: |
             token=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:circleci:pull" | jq -r '.token')
             curl -i -H "Authorization: Bearer $token" "https://registry-1.docker.io/v2/circleci/manifests/latest"             
             
