version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01

    working_directory: $HOME/circledir


    steps: 
      - checkout
      - run: |
             cd $HOME
             ls -al $HOME/circledir
      - run: |
             mkdir /tmp/artifacts
             bash $HOME/circledir/missman.sh
      - store_artifacts: 
          path: /tmp/artifacts
